version: '3.8'

services:
  backendserver1:
    build: ./BackendServer1
    ports:
      - "5001:8080"
    environment:
      - SERVER_NAME=BackendServer1

  backendserver2:
    build: ./BackendServer2
    ports:
      - "5002:8080"
    environment:
      - SERVER_NAME=BackendServer2

  backendserver3:
    build: ./BackendServer3
    ports:
      - "5003:8080"
    environment:
      - SERVER_NAME=BackendServer3

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - backendserver1
      - backendserver2
      - backendserver3
