version: '3.8'

services:
  backendserver1:
    build:
      context: .
      dockerfile: ./BackendServer1/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - SERVER_NAME=BackendServer1

  backendserver2:
    build:
      context: .
      dockerfile: ./BackendServer2/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - SERVER_NAME=BackendServer2

  backendserver3:
    build:
      context: .
      dockerfile: ./BackendServer3/Dockerfile
    ports:
      - "5003:8080"
    environment:
      - SERVER_NAME=BackendServer3

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - backendserver1
      - backendserver2
      - backendserver3
    
  CSETeamOSDB:
    image: postgres:latest
    container_name: CSETeamOSDB
    environment:
      - POSTGRES_DB=CSETeamOSDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "4332:5432"
    platform: linux/arm64  # Ensure proper image for M1

volumes:
  postgres_data:
